#!/bin/sh

export PYTHONPATH=$PWD/../

if ! [ -d "$1/etc" ]; then
	echo "You need to provide the path to a synthesized"
	echo "root filesystem as the first argument to this"
	echo "script."

	exit 1
fi

root="$1"
shift
python ../stackcheck/main.py controller.yml \
	--root "$root" -v -f facts.yml -I lenses "$@"
